name: Semantic Release

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
        - main
  workflow_dispatch:

  
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.AMM }}

    # Autoversioning and updating changelog:
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3.7.1
      with:
        github-token: ${{ secrets.AMM }}
        git-message: 'chore(release): {version}'
        git-user-name: 'Awesome Changelog Action'
        git-user-email: 'awesome_changelog@github.actions.com'
        preset: 'angular'
        tag-prefix: 'v'
        output-file: 'MY_CUSTOM_CHANGELOG.md'
        release-count: '10'
        version-file: './VERSION.json'
        version-path: './'
        skip-on-empty: 'false'
        skip-version-file: 'false'
        skip-commit: 'false'
        git-branch: 'my-maintenance-branch'
    # - name: Create Release
    #   uses: actions/create-release@v1
    #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ steps.changelog.outputs.tag }}
    #     release_name: ${{ steps.changelog.outputs.tag }}
    #     body: ${{ steps.changelog.outputs.clean_changelog }}
