# This workflow will auto-version when pull-requests are merged to main.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Semantic Versioning and Change Log

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:    
    - name: Git checkout
      uses: actions/checkout@v4
      with:
          token: ${{ secrets.AMM }}
          fetch-depth: 0

    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v5.2.1
      with:
        github-token: ${{ secrets.AMM }}
        version-file: 'VERSION.json'
        skip-on-empty: false
        git-user-name: 'ammounce'
        git-user-email: 'ammounce@gmail.com'
